config/routes.rb
require "resque_web"

Rails.application.routes.draw do
  mount ResqueWeb::Engine => "/resque_web"

  get '/auth/github/callback', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'

  # NOTE: we need build path without resources and use *id instead :id becouse
  # rails escape slash in url helpers, eg repo_path(repo) renders as user_name%2Frepo_name
  # instead user_name/repo_name
  scope :repos do
    scope ":owner_id/:repo_id", as: :repo do
      resources :branches, only: [] do
        resources :files, only: :index
        get "files/*id", to: "files#show", as: :file, constraints: {id: /.*/}
      end
    end

    get ":owner_id/:repo_id", to: "repos#show", as: :repo
    get "/", to: "repos#index", as: :repos
  end

  namespace :profile do
    root to: 'home#index'

    resources :billing, only: [:index] do
      resource :subscription, only: [:new, :create]
    end
  end

  resources :jobs, only: [:show]
  resources :builds, only: :create
  resources :repo_syncs, only: [:create]
  resources :repo_activations, only: [:update, :destroy]
  resources :github_events, only: [:create]

  get "/*id", to: 'pages#show', as: :page, format: false
  root 'home#index'

  match '*path', to: 'application#catch_404', via: :all
end

app/models/source_file.rb
class SourceFile < ActiveRecord::Base
  self.table_name = "files"

  attr_accessor :content

  belongs_to :branch
  has_many :smells, foreign_key: :file_id

  validates :branch, presence: true
  validates :path, presence: true

  def to_param
    path
  end

  # Smells grouped by categories with statistics
  #
  # Returns Hash {smell_type => count}
  #
  # TODO: move to finders?
  def smells_statistics
    @smells_statistics ||= smells.each_with_object(Hash.new(0)) do |smell, memo|
      memo[smell.analyzer] += 1
    end
  end
end

app/views/source_files/index.html.haml
- breadcrumb :source_files, @repo

- content_for(:header_icon, 'fa-file-text-o')

.row
  .col-md-12
    .panel.panel-default
      .panel-heading
        .panel-title-box

        %ul.panel-controls
          %li{style: 'width: 300px;'}
            %input.form-control.ui-autocomplete-input{placeholder: 'Search...', autocomplete: 'off'}
          %li
            %a.panel-fullscreen{href: '#'}
              %i.fa.fa-expand
          - if policy(@repo).manage?
            - branch_name = @build.present? ? @build.branch.name : @repo.default_branch.name
            %li
              = link_to builds_path(repo_id: @repo.id, branch: branch_name), remote: true, method: :post, class: 'js-build-repo' do
                %i.fa.fa-refresh

      .panel-body.panel-body-table
        .table-responsive
          - if @source_files.present?
            %table.table.table-bordered.table-striped
              %thead
                %tr
                  %th{style: 'width: 90px'} Marks
                  %th Source file
                  %th{style: 'width: 90px'} LOC
                  %th{style: 'width: 90px'} Smells
              %tbody
                = render partial: 'source_files/file', collection: @source_files
          - else
            There is no source files yet.

      - if @source_files.present?
        .panel-footer= will_paginate @source_files, renderer: BootstrapPagination::Rails

- content_for(:header_right_col) do
  = render 'shared/toggle_by_klasses_files', title: 'Show by source files'